-- Chat Konekto — Fase 5: salas de chat públicas.
-- Ejecutar después de las migraciones base de perfiles y sesiones.

CREATE TABLE IF NOT EXISTS public.salas_chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  activa boolean NOT NULL DEFAULT true,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mensajes_salas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sala_id bigint NOT NULL REFERENCES public.salas_chat(id) ON DELETE CASCADE,
  autor_id uuid NOT NULL REFERENCES public.perfiles_dk(id) ON DELETE CASCADE,
  contenido text NOT NULL CHECK (char_length(btrim(contenido)) BETWEEN 1 AND 250),
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.favoritos_salas (
  usuario_id uuid NOT NULL REFERENCES public.perfiles_dk(id) ON DELETE CASCADE,
  sala_id bigint NOT NULL REFERENCES public.salas_chat(id) ON DELETE CASCADE,
  creado_en timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (usuario_id, sala_id)
);

CREATE TABLE IF NOT EXISTS public.control_mensajes_salas (
  usuario_id uuid PRIMARY KEY REFERENCES public.perfiles_dk(id) ON DELETE CASCADE,
  ultimo_envio_en timestamptz NOT NULL
);

-- CREATE TABLE IF NOT EXISTS no modifica tablas que ya existían. Estas
-- columnas hacen la migración compatible con un intento anterior que haya
-- creado las tablas sin creado_en (o con otro nombre de fecha).
ALTER TABLE public.salas_chat
  ADD COLUMN IF NOT EXISTS creado_en timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.mensajes_salas
  ADD COLUMN IF NOT EXISTS creado_en timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.favoritos_salas
  ADD COLUMN IF NOT EXISTS creado_en timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_mensajes_salas_sala_fecha
  ON public.mensajes_salas (sala_id, creado_en DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_mensajes_salas_autor_fecha
  ON public.mensajes_salas (autor_id, creado_en DESC);

INSERT INTO public.salas_chat (nombre, slug)
VALUES
  ('Español', 'espanol'),
  ('Latino', 'latino'),
  ('Planeta Latino', 'planeta-latino'),
  ('Más de 30', 'mas-de-30'),
  ('Más de 20', 'mas-de-20'),
  ('Solo Amigos', 'solo-amigos'),
  ('Amor México', 'amor-mexico'),
  ('Gay', 'gay'),
  ('LGBT', 'lgbt'),
  ('Houston', 'houston'),
  ('México', 'mexico')
ON CONFLICT (nombre) DO UPDATE
SET slug = EXCLUDED.slug;

CREATE OR REPLACE FUNCTION public.limitar_mensajes_sala()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Serializa inserciones simultáneas en la misma sala para que el límite
  -- sea estricto incluso cuando llegan dos comentarios a la vez.
  PERFORM pg_advisory_xact_lock(hashtext('konekto:sala:' || NEW.sala_id::text));

  DELETE FROM public.mensajes_salas AS mensaje
  WHERE mensaje.id IN (
    SELECT id
    FROM public.mensajes_salas
    WHERE sala_id = NEW.sala_id
    ORDER BY creado_en DESC, id DESC
    OFFSET 12
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS mensajes_salas_max_12
  ON public.mensajes_salas;

CREATE TRIGGER mensajes_salas_max_12
AFTER INSERT ON public.mensajes_salas
FOR EACH ROW
EXECUTE FUNCTION public.limitar_mensajes_sala();

-- Limpieza inicial por si la tabla ya tenía datos antes de instalar el trigger.
WITH ordenados AS (
  SELECT
    id,
    row_number() OVER (
      PARTITION BY sala_id
      ORDER BY creado_en DESC, id DESC
    ) AS posicion
  FROM public.mensajes_salas
)
DELETE FROM public.mensajes_salas AS mensaje
USING ordenados
WHERE mensaje.id = ordenados.id
  AND ordenados.posicion > 12;

ALTER TABLE public.salas_chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes_salas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favoritos_salas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.control_mensajes_salas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS salas_chat_public_read ON public.salas_chat;
CREATE POLICY salas_chat_public_read
  ON public.salas_chat FOR SELECT
  USING (activa = true);

DROP POLICY IF EXISTS mensajes_salas_public_read ON public.mensajes_salas;
CREATE POLICY mensajes_salas_public_read
  ON public.mensajes_salas FOR SELECT
  USING (true);

DROP POLICY IF EXISTS favoritos_salas_no_direct_access ON public.favoritos_salas;
CREATE POLICY favoritos_salas_no_direct_access
  ON public.favoritos_salas FOR ALL
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS control_mensajes_salas_no_direct_access ON public.control_mensajes_salas;
CREATE POLICY control_mensajes_salas_no_direct_access
  ON public.control_mensajes_salas FOR ALL
  USING (false)
  WITH CHECK (false);

CREATE OR REPLACE FUNCTION public.obtener_salas_chat(p_session_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  viewer_id uuid;
  rooms jsonb;
BEGIN
  viewer_id := public.media_session_profile(p_session_token);
  IF viewer_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_SESSION');
  END IF;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', sala.id,
      'nombre', sala.nombre,
      'slug', sala.slug,
      'usuarios_activos', (
        SELECT count(DISTINCT mensaje.autor_id)
        FROM public.mensajes_salas AS mensaje
        WHERE mensaje.sala_id = sala.id
          AND mensaje.creado_en >= now() - interval '10 minutes'
      ),
      'es_favorita', EXISTS (
        SELECT 1
        FROM public.favoritos_salas AS favorito
        WHERE favorito.sala_id = sala.id
          AND favorito.usuario_id = viewer_id
      )
    )
    ORDER BY sala.nombre
  ), '[]'::jsonb)
  INTO rooms
  FROM public.salas_chat AS sala
  WHERE sala.activa = true;

  RETURN jsonb_build_object('ok', true, 'rooms', rooms);
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_sala_chat(
  p_session_token text,
  p_sala_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  viewer_id uuid;
  room_data jsonb;
  messages_data jsonb;
BEGIN
  viewer_id := public.media_session_profile(p_session_token);
  IF viewer_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_SESSION');
  END IF;

  SELECT jsonb_build_object(
    'id', sala.id,
    'nombre', sala.nombre,
    'slug', sala.slug,
    'usuarios_activos', (
      SELECT count(DISTINCT mensaje.autor_id)
      FROM public.mensajes_salas AS mensaje
      WHERE mensaje.sala_id = sala.id
        AND mensaje.creado_en >= now() - interval '10 minutes'
    ),
    'es_favorita', EXISTS (
      SELECT 1
      FROM public.favoritos_salas AS favorito
      WHERE favorito.sala_id = sala.id
        AND favorito.usuario_id = viewer_id
    )
  )
  INTO room_data
  FROM public.salas_chat AS sala
  WHERE sala.id = p_sala_id
    AND sala.activa = true;

  IF room_data IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'ROOM_NOT_FOUND');
  END IF;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', mensaje.id,
      'autor_id', perfil.id,
      'autor_alias', perfil.username,
      'avatar_url', perfil.avatar_url,
      'es_vip', coalesce(perfil.is_vip, perfil.es_vip, false),
      'contenido', mensaje.contenido,
      'creado_en', mensaje.creado_en
    )
    ORDER BY mensaje.creado_en DESC, mensaje.id DESC
  ), '[]'::jsonb)
  INTO messages_data
  FROM (
    SELECT *
    FROM public.mensajes_salas
    WHERE sala_id = p_sala_id
    ORDER BY creado_en DESC, id DESC
    LIMIT 12
  ) AS mensaje
  JOIN public.perfiles_dk AS perfil ON perfil.id = mensaje.autor_id;

  RETURN jsonb_build_object(
    'ok', true,
    'room', room_data,
    'messages', messages_data
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.enviar_mensaje_sala_seguro(
  p_session_token text,
  p_sala_id bigint,
  p_contenido text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  sender_id uuid;
  clean_content text;
  last_sent_at timestamptz;
  inserted_message public.mensajes_salas;
BEGIN
  sender_id := public.media_session_profile(p_session_token);
  IF sender_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_SESSION');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.salas_chat
    WHERE id = p_sala_id
      AND activa = true
  ) THEN
    RETURN jsonb_build_object('ok', false, 'code', 'ROOM_NOT_FOUND');
  END IF;

  clean_content := nullif(btrim(coalesce(p_contenido, '')), '');
  IF clean_content IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'EMPTY_MESSAGE');
  END IF;
  IF char_length(clean_content) > 250 THEN
    RETURN jsonb_build_object('ok', false, 'code', 'MESSAGE_TOO_LONG');
  END IF;

  -- El bloqueo evita dos envíos simultáneos del mismo usuario. El control
  -- vive separado del historial porque los mensajes viejos se eliminan.
  PERFORM pg_advisory_xact_lock(hashtext('konekto:sala-spam:' || sender_id::text));
  SELECT ultimo_envio_en
  INTO last_sent_at
  FROM public.control_mensajes_salas
  WHERE usuario_id = sender_id
  FOR UPDATE;

  IF last_sent_at IS NOT NULL
     AND last_sent_at >= now() - interval '5 seconds' THEN
    RETURN jsonb_build_object('ok', false, 'code', 'TOO_FAST');
  END IF;

  INSERT INTO public.mensajes_salas (sala_id, autor_id, contenido)
  VALUES (p_sala_id, sender_id, clean_content)
  RETURNING * INTO inserted_message;

  INSERT INTO public.control_mensajes_salas (usuario_id, ultimo_envio_en)
  VALUES (sender_id, inserted_message.creado_en)
  ON CONFLICT (usuario_id) DO UPDATE
  SET ultimo_envio_en = EXCLUDED.ultimo_envio_en;

  RETURN jsonb_build_object(
    'ok', true,
    'message', jsonb_build_object(
      'id', inserted_message.id,
      'creado_en', inserted_message.creado_en
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.alternar_favorito_sala(
  p_session_token text,
  p_sala_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  viewer_id uuid;
  is_favorite boolean;
BEGIN
  viewer_id := public.media_session_profile(p_session_token);
  IF viewer_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_SESSION');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.salas_chat
    WHERE id = p_sala_id
      AND activa = true
  ) THEN
    RETURN jsonb_build_object('ok', false, 'code', 'ROOM_NOT_FOUND');
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.favoritos_salas
    WHERE usuario_id = viewer_id
      AND sala_id = p_sala_id
  ) THEN
    DELETE FROM public.favoritos_salas
    WHERE usuario_id = viewer_id
      AND sala_id = p_sala_id;
    is_favorite := false;
  ELSE
    INSERT INTO public.favoritos_salas (usuario_id, sala_id)
    VALUES (viewer_id, p_sala_id)
    ON CONFLICT DO NOTHING;
    is_favorite := true;
  END IF;

  RETURN jsonb_build_object('ok', true, 'es_favorita', is_favorite);
END;
$$;

GRANT EXECUTE ON FUNCTION public.obtener_salas_chat(text)
  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_sala_chat(text, bigint)
  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enviar_mensaje_sala_seguro(text, bigint, text)
  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.alternar_favorito_sala(text, bigint)
  TO anon, authenticated;